Repository Portus-NFT-Marketplace/Portus-Frontend, pull requests merged in 2023-04, with the labels that each got.

#48 feature44-updated-creating-form
  package-lock.json
  package.json
  src/components/layouts/header/index.js
  src/components/layouts/header/signedInHeader.js
  src/components/pages/NFTCreatingPage/IPFSUploader.js
  src/components/pages/NFTCreatingPage/index.js
  src/components/pages/detailPage/index.js
  src/components/pages/homePage/index.js
  src/components/pages/myNFTPage/index.js
  src/components/pages/shared/general/CardNFT.js
Labels: ready to review

#49 feature45-foundation-page
  src/Routers.js
  src/components/layouts/header/index.js
  src/components/layouts/header/signedInHeader.js
  src/components/pages/foundationPage/detailFoundation.js
  src/components/pages/foundationPage/index.js
Labels: ready to review

#50 feature46-updated-detail-page
  src/components/layouts/header/index.js
  src/components/layouts/header/signedInHeader.js
  src/components/pages/detailPage/index.js
  src/components/pages/detailPage/style.css
  src/components/pages/foundationPage/index.js
Labels: ready to review

#51 feature47-about-us-page
  src/Routers.js
  src/components/layouts/header/index.js
  src/components/layouts/header/signedInHeader.js
  src/components/pages/aboutUsPage/favicon.ico
  src/components/pages/aboutUsPage/index.js
  src/components/pages/aboutUsPage/style.css
Labels: ready to review

#52 updated-about-us-page
  src/components/pages/aboutUsPage/index.js
  src/components/pages/foundationPage/detailFoundation.js
  src/components/pages/foundationPage/index.js
Labels: UI/UX design, ready to review

#53 feature48-footer
  src/App.js
  src/Routers.js
  src/components/layouts/footer/index.js
  src/components/layouts/index.js
  src/components/pages/aboutUsPage/index.js
  src/components/pages/foundationPage/index.js
  src/components/pages/homePage/index.js
Labels: ready to review

#54 feature49-verified-user-chain
  src/components/pages/shared/general/BuyButton.js
Labels: ready to review

#55 feature50-updated-logo
  public/favicon.ico
  src/components/layouts/footer/index.js
  src/components/layouts/header/index.js
  src/components/pages/aboutUsPage/favicon.ico
  src/components/pages/assets/banner-ads.jpg
  src/components/pages/assets/portus_logo.png
Labels: UI/UX design, ready to review

#56 feature51-cleaned-code
  src/App.js
  src/components/layouts/header/index.js
  src/components/layouts/header/signedInHeader.js
  src/components/pages/NFTCreatingPage/IPFSUploader.js
  src/components/pages/NFTCreatingPage/index.js
  src/components/pages/aboutUsPage/index.js
  src/components/pages/detailPage/index.js
  src/components/pages/homePage/carousel.js
  src/components/pages/homePage/index.js
  src/components/pages/loginPage/index.js
  src/components/pages/loginPage/loggedOutFoundation.js
  src/components/pages/loginPage/styles.css
  src/components/pages/myNFTPage/index.js
  src/components/pages/shared/general/ButtonFilter.js
  src/components/pages/shared/general/BuyButton.js
  src/components/pages/shared/general/ImageNFT.js
  src/components/pages/shared/general/MetaMaskButton.js
  src/index.js
Labels: ready to review

#57 feature52-added-ads
  src/components/pages/aboutUsPage/index.js
  src/components/pages/assets/ads/ads1.jpg
  src/components/pages/assets/ads/ads2.jpg
  src/components/pages/assets/ads/ads3.jpg
  src/components/pages/assets/ads/ads4.jpg
  src/components/pages/homePage/carouselAds.js
  src/components/pages/homePage/index.js
Labels: UI/UX design, ready to review

#59 feat54-fixed-foundation
  src/App.js
  src/components/pages/foundationPage/detailFoundation.js
  src/components/pages/foundationPage/index.js
  src/components/pages/homePage/carousel.js
  src/components/pages/homePage/index.js
  src/components/pages/loginPage/index.js
  src/components/pages/myNFTPage/index.js
Labels: ready to review

#60 feature55-fixed-carousel
  src/components/pages/homePage/carousel.js
  src/components/pages/shared/general/CardNFT.js
Labels: ready to review

#61 fixed-carousel
  src/components/pages/homePage/carousel.js
Labels: ready to review

#62 feature57-added-more-feat
  src/components/pages/NFTCreatingPage/index.js
  src/components/pages/detailPage/index.js
  src/components/pages/shared/general/EditButton.js
Labels: ready to review

#63 feature58-disabled-buy-button
  src/components/pages/detailPage/index.js
Labels: ready to review

#65 Change from ETH to AVAX
  src/components/pages/NFTCreatingPage/index.js
  src/components/pages/detailPage/index.js
  src/components/pages/shared/general/BuyButton.js
  src/components/pages/shared/general/CardNFT.js
Labels: approved

#64 Modify foundation detail page
  package-lock.json
  package.json
  src/components/pages/NFTCreatingPage/index.js
  src/components/pages/detailPage/index.js
  src/components/pages/foundationPage/detailFoundation.js
  src/components/pages/shared/general/BuyButton.js
  src/components/pages/shared/general/CardNFT.js
Labels: approved

#66 refactor-code
  src/components/pages/foundationPage/detailFoundation.js
Labels: ready to review

#67 feat61-fixed-NFT-img
  src/components/pages/shared/general/ImageNFT.js
  src/components/pages/shared/general/styles/NFTImg.css
Labels: ready to review
